name: Starter Workflow Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

    inputs:
      name:
        description: 'Person to great'
        default: 'World'
        required: true

jobs:
  first_demo_job:
    runs-on: ubuntu-latest
    name: display variables
    steps:
      - name: Show the demo running
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: GitHub Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4
  second_demo_job:
    runs-on: ubuntu-latest
    name: greeting msg
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
