name: Starter Workflow Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    inputs:
      name:
        description: 'Person to great'
        default: 'World'
        required: true
      environment:
#         type: environment
#         description: Select the environment
#       boolean:
#         type: boolean
#         description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - sandbox
        - dev
        - prod
      

jobs:
  first_demo_job:
    runs-on: ubuntu-latest
    name: display variables
    steps:
      - name: Show the demo running
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: GitHub Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4
  second_demo_job:
    runs-on: ubuntu-latest
    name: greeting msg
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
        
      - name: Run one line script
        run: echo Hello, World!
        
      - name: Run multiline script
        run: |
          echo 1. What is in this directory?
          ls -a
          echo
          cd ..
          ls -a
          echo
          echo 2. Goto Github-Actions
          cd Github-Actions
          ls -a
          echo
          echo 3. Goto scripts folder
          cd scripts
          ls -a
          echo
          echo 4. Goto addition.sh file
          touch addition.sh
          echo
  third_demo_job:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
  
    
