name: Starter Workflow Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    inputs:
      name:
        description: 'Person to great'
        default: 'World'
        required: true
#       environment:
#         type: environment
#         description: Select the environment
#       boolean:
#         type: boolean
#         description: True or False
      choice_stage:
        type: choice
        description: Make a choice for stage
        options:
        - all
        - sandbox
        - dev
        - prod
      choice_region:
        type: choice
        description: Make a choice for region
        options:
        - all
        - ap-south-1
        - us-east-2
        - ap-northeast-2 
        - eu-central-1
      choice_service:
        type: choice
        description: Make a choice for service
        options:
        - all
        - auth
        - account
        - part
        - document
         
        
      

jobs:
  first_demo_job:
    runs-on: ubuntu-latest
    name: display variables
    steps:
      - name: Show the demo running
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: GitHub Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4
  second_demo_job:
    runs-on: ubuntu-latest
    name: greeting msg
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
        
      - name: Run one line script
        run: echo Hello, World!    
  third_demo_job:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
            echo "choice is ${{ github.event.inputs.choice_stage }}" / ${{ inputs.choice_stage }}
            echo "choice is ${{ github.event.inputs.choice_region }}" / ${{ inputs.choice_region }}
            echo "choice is ${{ github.event.inputs.choice_service }}" / ${{ inputs.choice_service }}
  
    
