name: Starter Workflow Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    inputs:
      name:
        description: 'Person to great'
        default: 'World'
        required: true
      

jobs:
  first_demo_job:
    runs-on: ubuntu-latest
    name: display variables
    steps:
      - name: Show the demo running
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: GitHub Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4
  second_demo_job:
    runs-on: ubuntu-latest
    name: greeting msg
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
        
      - name: Run one line script
        run: echo Hello, World!
        
      - name: Run multiline script
        run: |
          echo 1. What is in this directory?
          cd Github-Actions/scripts/
           ls -a
          echo
          cd scripts/
          ls -a
          echo
  third_demo_job:
      runs-on: ubuntu-latest
      name: Run script
      steps: 
        - uses: actions/checkout@v2
        - name: Run a addition script
          run: ./ .github/Github-Actions/scripts/addition.sh
          shell: bash
  
