name: deploy Demo

on:
   workflow_dispatch:

    inputs:
      
      choice_stage:
        type: choice
        description: Make a choice for stage
        options:
     #   - all
        - sandbox
        - dev
        - prod
      choice_region:
        type: choice
        description: Make a choice for region
        default: ""
        required: false
        options:
        - all
        - ap-south-1
        - us-east-2
        - ap-northeast-2 
        - eu-central-1
      choice_service:
        type: choice
        description: Make a choice for service
        default: ""
        required: false
        options:
        - all
        - auth
        - account
        - part
        - document
      handler:
        description: 'Enter handler name'
        default: ""
        required: false
        type: string
         
        
      

jobs:
   deploy_job:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: display message
        run: | 
            echo "stage is ${{ github.event.inputs.choice_stage }}" 
            echo "region is ${{ github.event.inputs.choice_region }}"
            echo "service is ${{ github.event.inputs.choice_service }}"
            echo "Function is ${{github.event.inputs.handler }}"
