name: deploy-all

on:
  workflow_dispatch:

  inputs:
      name:

      choice_stage:
      type: choice
      description: Make a choice for stage
      options:
        - sandbox
        - dev
        - prod
        - all
        
      choice_region:
        type: choice
        description: Make a choice for region
        options:
          - ap-south-1
          - us-east-2
          - ap-northeast-2
          - eu-central-1
          - all
          
      choice_service:
        type: choice
        description: Make a choice for service
        options:
          - auth
          - account
          - part
          - document
          - all
          
      handler:
        description: Enter handler name
        default: ""
        required: false
        type: string

jobs:
  start_deploy:
    name: build-n-deploy-services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
   
      - name: display
        run: |
         echo "Stage is ${{ github.event.inputs.choice_stage }}"
         echo "Region is ${{ github.event.inputs.choice_region }}"
         echo "Service is ${{ github.event.inputs.choice_service }}"
         echo "Handler name is ${{ github.event.inputs.handler }}"



