name: Deploy-test

env:
  GO_VERSION: '1.18'
  GOLANGCI_VERSION: 'latest'
  KNYO_DIRECTORY: './'

  NIL: ""

on:
  workflow_dispatch:
    inputs:
      choice_stage:
        type: choice
        description: Make a choice for stage
        options:
          - sandbox
          - dev
          - prod

      choice_region:
        type: choice
        description: Make a choice for region
        default: ""
        required: false
        options:
          - all
          - ap-south-1
          - us-east-2
          - ap-northeast-2
          - eu-central-1

      choice_service:
        type: choice
        description: Make a choice for service
        default: ""
        required: false
        options:
          - all
          - auth
          - account
          - part
          - document

      handler:
        description: Enter handler name
        default: ""
        required: false
        type: string

jobs:
  start_deploy:
    name: build-n-deploy-services
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout the code
        uses: actions/checkout@v2

#       - name: Find the Go Build Cache
#         id: go
#         run: echo "::set-output name=cache::$(go env GOCACHE)"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

#       - name: Install Serverless dependencies
#         uses: bahmutov/setup-npm@v1
#         with:
#           npm-version: 6.x

      - name: Install NPM 6.x
        run: npm install -g npm@6
          
      - name: Install npm dependencies
        run: npm install
        working-directory: ${{ env.KNYO_DIRECTORY }}
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: github.event.inputs.choice_stage != ''
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_${{ github.event.inputs.choice_stage }}_UPPERCASE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_${{ github.event.inputs.choice_stage }}_UPPERCASE }}
          aws-region: ${{ github.event.inputs.choice_region }}

      - name: Deploy start
        run: |
          STAGE="${{ github.event.inputs.choice_stage }}"
          REGION="${{ github.event.inputs.choice_region }}"
          SERVICE="${{ github.event.inputs.choice_service }}"
          HANDLER="${{ github.event.inputs.handler }}"
                
          echo " -t $STAGE -r $REGION -s $SERVICE -f $HANDLER "
